### ISSUE TITLE
В собранный priv.js не добавляются пути к сорцам

### ISSUE THREAD

**Issue by ignovak** [enb-make/enb#25]
Хочется, чтобы было по аналогии с css-файлами:

``` css
/* ../wbr/i-global__wbr.css: begin */ /**/
    wbr
    {
        display: inline-block;
    }
/* ../wbr/i-global__wbr.css: end */ /**/
```
