### ISSUE TITLE
Теряется кавычка при сборке css с заинлайненным svg

### ISSUE THREAD

**Issue by ignovak** [enb-make/enb#28]
Если в исходном css'е есть заинлайненный svg, включенный в одинарные кавычки, и если внутри этого svg есть круглые скобки, кавычка в начале теряется.
Т.е.

``` css
.domik_type_popup
{
    background-image: url('data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20url(%23l)20fill%3D%22none%22%2F%3E%3C%2Fsvg%3E');
}
```

станет

``` css
.domik_type_popup
{
    background-image: url(data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20url(%23l)20fill%3D%22none%22%2F%3E%3C%2Fsvg%3E');
}
```
